### ISSUE TITLE
Update to v1.14.0 from v1.13.5 : NoMethodError: undefined method `url' for nil:NilClass from /var/www/shirasagi/app/models/concerns/cms/content.rb:184:in `url'

### ISSUE THREAD

**Issue by tatsuyasenbom** [shirasagi/shirasagi#4019]
# 環境

```sh
$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
$ mongo --version
MongoDB shell version v4.4.7
Build Info: {
    "version": "4.4.7",
    "gitVersion": "abb6b9c2bf675e9e2aeaecba05f0f8359d99e203",
    "openSSLVersion": "OpenSSL 1.0.1e-fips 11 Feb 2013",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "rhel70",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
$ rvm -v
rvm 1.29.12-next (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
```

# 現象
* [SHIRASAGI 開発マニュアル SHIRASAGI の更新](https://shirasagi.github.io/updation/manual.html)に基づき、`v1.13.5`から`v1.14.0`へアップデートする中で`bundle exec rake ss:migrate`を実行した際に以下エラーを確認しました。

	```sh
	$ bundle exec rake ss:migrate
	:
	rake aborted!
	NoMethodError: undefined method `url' for nil:NilClass
	/var/www/shirasagi/app/models/concerns/cms/content.rb:184:in `url'
	/var/www/shirasagi/app/models/concerns/cms/addon/form/page.rb:54:in `render_html'
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object/try.rb:19:in `public_send'
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object/try.rb:19:in `try!'
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object/try.rb:8:in `try'
	/var/www/shirasagi/app/models/concerns/cms/model/page.rb:187:in `new_size_input'
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object/try.rb:19:in `public_send'
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object/try.rb:19:in `try!'
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/object/try.rb:8:in `try'
	/var/www/shirasagi/lib/migrations/cms/20210628000000_set_cms_pages_size.rb:11:in `block (2 levels) in change'
	/var/www/shirasagi/lib/migrations/cms/20210628000000_set_cms_pages_size.rb:10:in `each'
	/var/www/shirasagi/lib/migrations/cms/20210628000000_set_cms_pages_size.rb:10:in `block in change'
	/var/www/shirasagi/lib/migrations/cms/20210628000000_set_cms_pages_size.rb:9:in `each'
	/var/www/shirasagi/lib/migrations/cms/20210628000000_set_cms_pages_size.rb:9:in `each_slice'
	/var/www/shirasagi/lib/migrations/cms/20210628000000_set_cms_pages_size.rb:9:in `change'
	/var/www/shirasagi/app/models/ss/migration.rb:180:in `apply'
	/var/www/shirasagi/app/models/ss/migration.rb:159:in `block in apply_all'
	/var/www/shirasagi/app/models/ss/migration.rb:159:in `each'
	/var/www/shirasagi/app/models/ss/migration.rb:159:in `apply_all'
	/var/www/shirasagi/app/models/ss/migration.rb:17:in `migrate'
	/var/www/shirasagi/lib/tasks/ss/migrate.rake:3:in `block (2 levels) in <main>'
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:22:in `eval'
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:22:in `<main>'
	Tasks: TOP => ss:migrate
	(See full trace by running task with --trace)
	```

# 前提
* `v1.13.5`は[shirasagi/shirasagi/master/bin/install.sh](https://raw.githubusercontent.com/shirasagi/shirasagi/master/bin/install.sh)を使ってインストールしました。
* インストール後にWeb管理画面から以下で投入されるデモデータは削除した状態で`v1.14.0`へアップデートを試みていました。

	```sh
	:
	bundle exec rake ss:create_site data="{ name: \"自治体サンプル\", host: \"www\", domains: \"${SS_HOSTNAME}\" }"
	bundle exec rake ss:create_site data="{ name: \"企業サンプル\", host: \"company\", domains: \"${SS_HOSTNAME}:${PORT_COMPA}\" }"
	bundle exec rake ss:create_site data="{ name: \"子育て支援サンプル\", host: \"childcare\", domains: \"${SS_HOSTNAME}:${PORT_CHILD}\" }"
	bundle exec rake ss:create_site data="{ name: \"オープンデータサンプル\", host: \"opendata\", domains: \"${SS_HOSTNAME}:${PORT_OPEND}\" }"
	bundle exec rake ss:create_site data="{ name: \"ＬＰサンプル\", host: \"lp_\", domains: \"${SS_HOSTNAME}:${PORT_LPSPL}\" }"
	bundle exec rake db:seed name=demo site=www
	bundle exec rake db:seed name=company site=company
	bundle exec rake db:seed name=childcare site=childcare
	bundle exec rake db:seed name=opendata site=opendata
	bundle exec rake db:seed name=lp site=lp_
	:
	```

# 回避
* 以下を実施し一時的に上記現象を回避し、一旦アップデートできることを確認しました。

	```sh
	$ vim /var/www/shirasagi/app/models/concerns/cms/addon/form/page.rb
	module Cms::Addon::Form::Page
		:
		def render_html(registers = nil)
			return html if form.blank?
			
			registers ||= {
				cur_site: site,
				#cur_path: url, # コメントアウト
				cur_path: nil, # 追記
				cur_page: self
			}
		
			form.render_html(self, registers).html_safe
		end
		:
	end
	$ vim /var/www/shirasagi/lib/ss/liquid_part_drop.rb
	:
	class SS::LiquidPartDrop < Liquid::Drop
		:
		def find(site)
			#cache.find { |item| item.site.id == site.id } # 新たに発生した「NoMethodError: undefined method `id' for nil:NilClass」を回避するためコメントアウト
			nil # 追記
		end
		:
	end
	```

**Comment by itowtips** [comment]
以下の手順で再現しました。

~~~
1. シラサギをインストールして自治体サンプルを投入

# bundle exec rake ss:create_site data='{ name: "サイト名", host: "www", domains: "localhost:3000" }'
# bundle exec rake db:seed name=demo site=www

2. 管理画面の システム設定＞サイト一覧 より 自治体サイトを削除

3. マイグレーション実行

# rake ss:migrate
rake aborted!
NoMethodError: undefined method `url' for nil:NilClass
/var/www/shirasagi/app/models/concerns/cms/content.rb:184:in `url'
/var/www/shirasagi/app/models/concerns/cms/addon/form/page.rb:54:in `render_html'
~~~

原因は以下です。
 - 管理画面からサイトを削除しても、関連するページはDBに残る。
 - 20210628000000_set_cms_pages_size.rb にて、全てのページの bytesize をDB保存しようとするが、削除されたサイトのページも対象となる。
 - 上記マイグレーションにて、定型フォームが設定されている場合 render_html メソッドが呼ばれるが、site が削除されているため nil 参照を起こす。

**Comment by itowtips** [comment]
https://github.com/shirasagi/shirasagi/pull/4020 にて修正しました。
修正を適用し、もう一度  rake ss:migrate して頂ければ、エラーなく完了すると思います。

**Comment by tatsuyasenbom** [comment]
素早いご対応ありがとうございます！エラーが解消されていることを確認しました！！！
