### ISSUE TITLE
Update to v1.14.2 from v1.14.1 : bundle exec rake assets:precompile -> Sprockets::FileNotFound: couldn't find file 'jquery.datetimepicker' with type 'application/javascript' & SassC::SyntaxError: Error: no mixin named box-shadow

### ISSUE THREAD

**Issue by tatsuyasenbom** [shirasagi/shirasagi#4090]
# 環境

```sh
$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
$ mongo --version
MongoDB shell version v4.4.7
Build Info: {
    "version": "4.4.7",
    "gitVersion": "abb6b9c2bf675e9e2aeaecba05f0f8359d99e203",
    "openSSLVersion": "OpenSSL 1.0.1e-fips 11 Feb 2013",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "rhel70",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
$ rvm -v
rvm 1.29.12-next (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
```

# 前提
* `v1.14.1`は[shirasagi/shirasagi/master/bin/install.sh](https://raw.githubusercontent.com/shirasagi/shirasagi/master/bin/install.sh)をベースに、MongoDBやRubyのバージョンを変更しインストールし、稼働していました。
* インストール後は初期状態のままで、デモデータを含め変更は行っていませんでした。

# 現象&解消までの流れ
* [SHIRASAGI 開発マニュアル SHIRASAGI の更新](https://shirasagi.github.io/updation/manual.html)に基づき、`v1.14.1`から`v1.14.2`へアップデート後、アップデートした直後の状態で`bundle exec rake assets:precompile`を実行した際に以下エラーを確認しました。
* 以下を実施し一時的に上記現象を回避し、一旦アップデートできることを確認しました。

	```sh
	$ systemctl stop nginx
	$ systemctl stop shirasagi-unicorn
	$ cd /var/www/shirasagi
	$ git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
	$ git branch
	master -> origin/master
	$ git fetch origin
	$ rm -rf vendor
	$ git reset --hard
	$ git pull
	$ bundle install --without development test
	:
	$ bundle exec rake ss:migrate
	:
	$ bundle exec rake assets:precompile
	Yarn executable was not detected in the system.
	Download Yarn at https://yarnpkg.com/en/docs/install
	I, [2021-08-31T15:57:39.121368 #18929]  INFO -- : Writing /var/www/shirasagi/public/assets/opendata/icon-user-c8ace0cadf4f82ffe6f0a12523e1c9cacda25cb337b1cd0039ce4e8de357e814.png
	:
	I, [2021-08-31T15:57:46.646457 #18929]  INFO -- : Writing /var/www/shirasagi/public/assets/cms/preview/datatables-a57c51a470fa56147ed689c35db3e979ad80ebd56805e418d6c617d94290ef7c.js.gz
	rake aborted!
	Sprockets::FileNotFound: couldn't find file 'jquery.datetimepicker' with type 'application/javascript'
	Checked in these paths: 
	  /var/www/shirasagi/app/assets/images
	  :
	  /var/www/shirasagi/public/assets/js
	/var/www/shirasagi/app/assets/javascripts/cms/preview/datetimepicker.js:1
	:
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:22:in `<main>'
	Tasks: TOP => assets:precompile
	(See full trace by running task with --trace)
	zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
	zlib(finalizer): the stream was freed prematurely.
	$ rm -rf app bin db doc lib spec vendor config/*/* public/assets*
	$ git reset --hard
	$ bundle install --without development test
	$ bundle exec rake ss:migrate
	$ bundle exec rake assets:precompile
	Yarn executable was not detected in the system.
	Download Yarn at https://yarnpkg.com/en/docs/install
	I, [2021-08-31T16:12:33.057728 #21128]  INFO -- : Writing /var/www/shirasagi/public/assets/opendata/icon-user-c8ace0cadf4f82ffe6f0a12523e1c9cacda25cb337b1cd0039ce4e8de357e814.png
	:
	I, [2021-08-31T16:12:58.343207 #21128]  INFO -- : Writing /var/www/shirasagi/public/assets/opendata/form-0a77c72d4f8ebca8e712dd12255b875fdc9ef6b8daf0004a4c4005133326a7bb.css.gz
	rake aborted!
	SassC::SyntaxError: Error: no mixin named box-shadow
	        on line 32:14 of app/assets/stylesheets/ss/print.scss
	>>     @include box-shadow(0 .5mm 2mm rgba(0, 0, 0, .3));

	   -------------^
	/var/www/shirasagi/app/assets/stylesheets/ss/print.scss:32
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/gems/sassc-2.3.0/lib/sassc/engine.rb:50:in `render'
	:
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
	.sheet {
	  border: 0;
	  border-radius: unset;
	  background: #fff;
	  page-break-after: always;
	}

	.vertical {
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
	:
	/var/www/shirasagi/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:22:in `<main>'
	Tasks: TOP => assets:precompile
	(See full trace by running task with --trace)
	$ vim app/assets/stylesheets/ss/print.scss
	:
	/* プレビュー用のスタイル */
	@media screen {
	  #main {
	    .wrap {
	      margin: 10px;
	    }
	  }

	  .sheet {
	    margin: 5mm;
	    //@include box-shadow(0 .5mm 2mm rgba(0, 0, 0, .3));
	    box-shadow: 0 .5mm 2mm rgba(0, 0, 0, .3);
	  }
	}
	:
	$ bundle exec rake assets:precompile
	Yarn executable was not detected in the system.
	Download Yarn at https://yarnpkg.com/en/docs/install
	I, [2021-08-31T16:27:04.313433 #21507]  INFO -- : Writing /var/www/shirasagi/public/assets/ss/print-96c3bbd53f924f38121de1681c2ef686390507f6f8a243420e94dec45412e5e4.css
	:
	I, [2021-08-31T16:27:04.857784 #21507]  INFO -- : Writing /var/www/shirasagi/public/assets/ss/style-5af61c01d031bbd090ca618467ecd4034e955b792254704ac885050eaa46c3ad.css.gz
	$ systemctl start shirasagi-unicorn
	$ systemctl start nginx
	```

**Comment by sunny4381** [comment]
@tatsuyasenbom すみません。書きかけで投稿してしまいました。
本件ですが、一時期、本現象の発生するコミットを master にマージしてしまっていましたが、
https://github.com/shirasagi/shirasagi/commit/0f05f12125c2ce1bb4e4d3ad310f5402d82c64ff にて修正されているかと思います。

**Comment by tatsuyasenbom** [comment]
0f05f12 を確認しました。

ご対応いただきありがとうございました。
