### ISSUE TITLE
CMS の管理画面が表示されない

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#424]
次のエラーが出て CMS の管理画面が表示されない。

```
F, [2015-05-12T20:12:18.931241 #29741] FATAL -- :
ActionView::Template::Error (undefined local variable or method `permission_level' for #<SS::User:0x0000000d7940e8>):
    15:         <%= link_to item.name, contents_path(item), class: "icon-node"%>
    16:         <nav class="tap-menu">
    17:           <%= link_to :"cms.content", contents_path(item) %>
    18:           <%= link_to :show, node_conf_path(cid: item) if item.allowed?(:read, @cur_user, site: @cur_site) %>
    19:           <%= link_to :edit, edit_node_conf_path(cid: item) if item.allowed?(:edit, @cur_user, site: @cur_site) %>
    20:           <%= link_to :preview, cms_preview_path(path: "#{item.filename}/"), target: :_blank %>
    21:           <%= link_to :view_site, item.full_url, target: :_blank %>
  app/models/cms/reference.rb:23:in `block (2 levels) in cms_role_permissions'
  app/models/cms/reference.rb:20:in `each'
  app/models/cms/reference.rb:20:in `block in cms_role_permissions'
  app/models/cms/reference.rb:19:in `cms_role_permissions'
  app/models/cms/addon/owner_permission.rb:50:in `block in allowed?'
  app/models/cms/addon/owner_permission.rb:49:in `each'
  app/models/cms/addon/owner_permission.rb:49:in `allowed?'
  app/views/cms/contents/index.html.erb:18:in `block in _app_views_cms_contents_index_html_erb__854754077766283184_111063480'
  app/views/cms/contents/index.html.erb:11:in `_app_views_cms_contents_index_html_erb__854754077766283184_111063480'

```

**Comment by sunny4381** [comment]
ユーザが、例えば「サイト管理者」、「記事編集権限」という 2 つの Role を持っており、各 Role が "read_private_article_pages" を持っている場合に発生するようです。

**Comment by sunny4381** [comment]
Pull Request を送りました。
#425

**Comment by sunny4381** [comment]
Spec を追加しました。
