### ISSUE TITLE
[v1.16.2] `bundle exec rake ss:migrate`時に`rake aborted! NoMethodError: undefined method 'full_url' for nil:NilClass`が発生

### ISSUE THREAD

**Issue by tatsuyasenbom** [shirasagi/shirasagi#4679]
# 経緯
1. 以下の`テスト環境`と`本番環境`上では`v1.16.1`が稼働していました。
2. `テスト環境`と`本番環境`のスペック及びミドルウェアは同じバージョンに揃えています。
3. `テスト環境`は`SHIRASAGI`の初回のインストールと各バージョンへのアップグレード操作のみを行っているため、本来の`SHIRASAGI`以外のデータは存在しません。
4. `テスト環境`で新しい`SHIRASAGI`へのアップデートが確認できてから`本番環境`のアップデートを実施しています。
5. 今回、上記4の`テスト環境`上でのアップデートでは問題は起きませんでしたが、`本番環境`にては`bundle exec rake ss:migrate`時に本現象が発生しました。
6. ちなみに`v1.16.0`から`v1.16.1`へのアップデート時には本現象は確認できませんでした。
7. `本番環境`でのみ本現象が起きていることから「日々の運用の中でCRUDされたデータが、本現象のトリガーになっている？」と疑っております。

# 現象

## テスト環境

```sh
[root@test]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@test]# ruby -v
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]
[root@test]#  bundle exec rails -v
Rails 6.1.4.1
[root@test]# mongo --version
MongoDB shell version v4.4.17
Build Info: {
    "version": "4.4.17",
    "gitVersion": "85de0cc83f4dc64dbbac7fe028a4866228c1b5d1",
    "openSSLVersion": "OpenSSL 1.0.1e-fips 11 Feb 2013",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "rhel70",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
[root@test]# bundle exec rake ss:migrate
# Total 2 pages
find 100 pages...
:
[root@test]#
```

## 本番環境

```sh
[root@production]# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
[root@production]# ruby -v
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]
[root@production]#  bundle exec rails -v
Rails 6.1.4.1
[root@production]# mongo --version
MongoDB shell version v4.4.17
Build Info: {
    "version": "4.4.17",
    "gitVersion": "85de0cc83f4dc64dbbac7fe028a4866228c1b5d1",
    "openSSLVersion": "OpenSSL 1.0.1e-fips 11 Feb 2013",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "rhel70",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
[root@production]# bundle exec rake ss:migrate
# Total 2 pages
find 100 pages...
rake aborted!
NoMethodError: undefined method `full_url' for nil:NilClass
/var/www/shirasagi/app/models/concerns/cms/model/node.rb:274:in `validate_invalid_filename'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:603:in `catch'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:199:in `block in halting'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:512:in `each'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:512:in `invoke_before'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:105:in `run_callbacks'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/bundler/gems/mongoid-ca2d42c4a886/lib/mongoid/interceptable.rb:135:in `run_callbacks'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:824:in `_run_validate_callbacks'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activemodel-6.1.4.1/lib/active_model/validations.rb:406:in `run_validations!'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activemodel-6.1.4.1/lib/active_model/validations/callbacks.rb:117:in `block in run_validations!'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:106:in `run_callbacks'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/bundler/gems/mongoid-ca2d42c4a886/lib/mongoid/interceptable.rb:135:in `run_callbacks'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:824:in `_run_validation_callbacks'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activemodel-6.1.4.1/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activemodel-6.1.4.1/lib/active_model/validations.rb:337:in `valid?'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/bundler/gems/mongoid-ca2d42c4a886/lib/mongoid/validatable.rb:99:in `valid?'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/activemodel-6.1.4.1/lib/active_model/validations.rb:374:in `invalid?'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/bundler/gems/mongoid-ca2d42c4a886/lib/mongoid/persistable/updatable.rb:110:in `prepare_update'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/bundler/gems/mongoid-ca2d42c4a886/lib/mongoid/persistable/updatable.rb:134:in `update_document'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/bundler/gems/mongoid-ca2d42c4a886/lib/mongoid/persistable/savable.rb:27:in `save'
/var/www/shirasagi/lib/tasks/facility/page.rake:12:in `block (4 levels) in <main>'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/bundler/gems/mongoid-ca2d42c4a886/lib/mongoid/contextual/mongo.rb:729:in `yield_document'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/bundler/gems/mongoid-ca2d42c4a886/lib/mongoid/contextual/mongo.rb:156:in `block in each'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/mongo-2.15.1/lib/mongo/collection/view/iterable.rb:79:in `block in each'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/mongo-2.15.1/lib/mongo/cursor.rb:167:in `block in each'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/mongo-2.15.1/lib/mongo/cursor.rb:165:in `loop'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/mongo-2.15.1/lib/mongo/cursor.rb:165:in `each'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/mongo-2.15.1/lib/mongo/collection/view/iterable.rb:78:in `each'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/bundler/gems/mongoid-ca2d42c4a886/lib/mongoid/contextual/mongo.rb:155:in `each'
/var/www/shirasagi/lib/tasks/facility/page.rake:11:in `block (3 levels) in <main>'
/var/www/shirasagi/lib/tasks/facility/page.rake:8:in `each'
/var/www/shirasagi/lib/tasks/facility/page.rake:8:in `each_slice'
/var/www/shirasagi/lib/tasks/facility/page.rake:8:in `block (2 levels) in <main>'
/var/www/shirasagi/lib/tasks/ss.rb:7:in `invoke_task'
/var/www/shirasagi/lib/migrations/facility/20220824000000_search_cache.rb:7:in `change'
/var/www/shirasagi/app/models/ss/migration.rb:180:in `apply'
/var/www/shirasagi/app/models/ss/migration.rb:159:in `block in apply_all'
/var/www/shirasagi/app/models/ss/migration.rb:159:in `each'
/var/www/shirasagi/app/models/ss/migration.rb:159:in `apply_all'
/var/www/shirasagi/app/models/ss/migration.rb:17:in `migrate'
/var/www/shirasagi/lib/tasks/ss/migrate.rake:3:in `block (2 levels) in <main>'
/var/www/shirasagi/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/rvm/rubies/ruby-3.0.4/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/rubies/ruby-3.0.4/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => facility:clear_search_cache
(See full trace by running task with --trace)
[root@production]#
```

**Comment by sunny4381** [comment]
@tatsuyasenbom 報告ありがとうございます。連絡が遅くなりましたが、v1.16.2 の追加修正をリリースしました。
GitHub から stable 版を取得し直してください。

**Comment by tatsuyasenbom** [comment]
@sunny4381 様 ご対応いただきありがとうございます。当該コミットにて本現象が改善することを確認しました。ご対応いただきありがとうございました！！！！
