### ISSUE TITLE
ページ書き出しでエラーが発生

### ISSUE THREAD

**Issue by sunny4381** [shirasagi/shirasagi#594]
リソースの厳しい環境で、ページ書き出しを実行すると、次のようなエラーが発生する。

```
-- Error
The operation: #<Moped::Protocol::GetMore
  @length=54
  @request_id=210377
  @response_to=0
  @op_code=2005
  @reserved=0
  @full_collection_name="ss_miyazaki.cms_pages"
  @limit=0
  @cursor_id=907594734948>
failed with error "cursor 907594734948 not found"
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/operation/read.rb:50:in `block in execute'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/node.rb:594:in `[]'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/node.rb:594:in `block (2 levels) in flush'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/node.rb:593:in `map'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/node.rb:593:in `block in flush'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/node.rb:617:in `block in logging'
/usr/local/rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.2.2/gems/activesupport-4.2.2/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/instrumentable.rb:31:in `instrument'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/node.rb:616:in `logging'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/node.rb:587:in `flush'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/node.rb:391:in `process'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/operation/read.rb:48:in `execute'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/node.rb:648:in `read'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/node.rb:223:in `get_more'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/cursor.rb:46:in `get_more'
/usr/local/rvm/gems/ruby-2.2.2/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:238:in `block in get_more'
/usr/local/rvm/gems/ruby-2.2.2/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:135:in `with_cache'
/usr/local/rvm/gems/ruby-2.2.2/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:238:in `get_more'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/cursor.rb:31:in `each'
/usr/local/rvm/gems/ruby-2.2.2/gems/moped-2.0.4/lib/moped/query.rb:77:in `each'
/usr/local/rvm/gems/ruby-2.2.2/gems/mongoid-4.0.2/lib/mongoid/contextual/mongo.rb:122:in `each'
/usr/local/rvm/gems/ruby-2.2.2/gems/mongoid-4.0.2/lib/mongoid/contextual.rb:20:in `each'
/var/www/miyazaki/app/controllers/cms/agents/tasks/pages_controller.rb:19:in `generate'
...
```

**Comment by sunny4381** [comment]
100 件ずつレコードを読むようにしてみたところ、エラーは解消しました。
1000 件でもエラーは発生しませんが、`vmstat 5` コマンドの出力から 2 桁の si/so をたまに観測しましたので、100 件ずつとしました。

**Comment by tany** [comment]
`find_each` どうでしょう。
http://blog.livedoor.jp/sasata299/archives/51882704.html

**Comment by sunny4381** [comment]
どうも Mongoid で find_each は、存在しないようです。
ここら辺りを参考に、独自実装としました。
https://github.com/mongoid/mongoid/issues/1334

**Comment by sunny4381** [comment]
find_each / find_in_batches を SS::Document に実装しました。
厳密には Rails のそれとは仕様が異なりますが、同じように利用できると思います。
