### ISSUE TITLE
Rspec で SimpleCov::Formatter::HTMLFormatter failed

### ISSUE THREAD

**Issue by tany** [shirasagi/shirasagi#843]
~~~
$ rspec
Formatter SimpleCov::Formatter::HTMLFormatter failed with Encoding::CompatibilityError:
 incompatible character encodings: ASCII-8BIT and UTF-8 ((erb):18:in `concat')
~~~

その後のテストは通る。

**Comment by sunny4381** [comment]
スタックトレースを全て出力してみた:

```
Formatter SimpleCov::Formatter::HTMLFormatter failed with Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8
(erb):18:in `concat'
(erb):18:in `block in formatted_source_file'
(erb):14:in `each'
(erb):14:in `each_with_index'
(erb):14:in `formatted_source_file'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `result'
/usr/local/rvm/gems/ruby-2.3.0/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:56:in `formatted_source_file'
(erb):36:in `block (2 levels) in format'
(erb):35:in `each'
(erb):35:in `block in format'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `result'
/usr/local/rvm/gems/ruby-2.3.0/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:23:in `block in format'
/usr/local/rvm/gems/ruby-2.3.0/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:22:in `open'
/usr/local/rvm/gems/ruby-2.3.0/gems/simplecov-html-0.10.0/lib/simplecov-html.rb:22:in `format'
/usr/local/rvm/gems/ruby-2.3.0/gems/simplecov-0.11.2/lib/simplecov/formatter/multi_formatter.rb:8:in `block in format'
/usr/local/rvm/gems/ruby-2.3.0/gems/simplecov-0.11.2/lib/simplecov/formatter/multi_formatter.rb:6:in `map'
/usr/local/rvm/gems/ruby-2.3.0/gems/simplecov-0.11.2/lib/simplecov/formatter/multi_formatter.rb:6:in `format'
/usr/local/rvm/gems/ruby-2.3.0/gems/simplecov-0.11.2/lib/simplecov/result.rb:47:in `format!'
/usr/local/rvm/gems/ruby-2.3.0/gems/simplecov-0.11.2/lib/simplecov/configuration.rb:172:in `block in at_exit'
/usr/local/rvm/gems/ruby-2.3.0/gems/simplecov-0.11.2/lib/simplecov/defaults.rb:67:in `block in <top (required)>'
```

**Comment by sunny4381** [comment]
`app/models/concerns/gws/reference/role.rb` のカバレッジを HTML 形式で出力している最中に発生するようだ。

**Comment by sunny4381** [comment]
なぜか文字コードが "ASCII-8BIT" になっていて、"UTF-8" の文字列を連結しようとしてエラーになっている。
テストの最中に文字コードを "ASCII-8BIT" に変更して、基に戻していないとかないですか？

**Comment by sunny4381** [comment]
さっきのは間違い。

`/usr/local/rvm/gems/ruby-2.3.0/gems/simplecov-html-0.10.0/views/source_file.erb` の `<code class="ruby"><%= CGI.escapeHTML(line.src.chomp) %></code>` というところでエラーが起きている。

`line.src.chomp` の文字コードは、常に "ASCII-8BIT" であるのに、`CGI.escapeHTML(line.src.chomp)` は "ASCII-8BIT" だったり "UTF-8" だったりする。

`line.src` はソースコード内の行を格納しているが、日本語が含まれる行であったとしても、文字コードは "ASCII-8BIT" である。この仕様が正しいのかどうか...。

`CGI.escapeHTML(line.src.chomp)` に日本語を含む "ASCII-8BIT" な文字列を与えると、"ASCII-8BIT" のままだったり "UTF-8" になったりする。
